language: cpp
compiler:
    - g++
env:
  - COMPILER: g++
  - COMPILER: c++
  - COMPILER: cpp

before_script:
    - echo "compiling with: $COMPILER"
    - ls .
script: $COMPILER -o vektor main.cpp Vektor.cpp
